name: simple_http_api
description:
  A package extends the official http package with the features of cancellation, timeout and EventSource.
  No complicated concepts and redundant functions, just API requests.
homepage: https://github.com/SimonWang9610/api
repository: https://github.com/SimonWang9610/api
issue_tracker: https://github.com/SimonWang9610/api/issues

version: 1.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  http_parser: ^4.0.2
  mime: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
